config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  "/about",   to: "static_pages#about"
  get '/signup'  => 'users#new'
  resources :users

  resources :recipes, only: %w[index show]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :author, class_name: "User"

  has_many :ingredients
  
  enum difficulty: {
    beginner: 0,
    intermediate: 1,
    advanced: 2,
    expert: 3
  }
  validates :difficulty, presence: true
  validates :name, presence: true

  scope :favorites, -> { where(favorite: true) }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :recipes, foreign_key: 'author_id'

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: {message: "%{value} already exists!"}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX }
  validates :email, uniqueness: {message: "%{value} is already in use."}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.first
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = @current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)    # Not the final implementation!

    if @user.save
      # Handle a successful save by creating a new User
      # redirect to User welcome page
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'hklogocircle.png', size: "75x75", class: "d-inline-block align-text-top rounded-circle"%>
    </a>
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
        data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false"
        aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <li><%= link_to "Home", root_path %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "About", about_path %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Login", "#" %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Signup", signup_path %></li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header>
     <%= render "layouts/navbar" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>This is a placeholder for a recipe index page</h1>


<h2>Recipes of Foosta</h2>
  <% @recipes.each do |recipe| %>
   <li><%= recipe.name %></li>
   <%= link_to "View Recipe", recipe_path(id: recipe.id) %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<h2><%= @recipe.difficulty %> </h2>

<body>
  <%= @recipe.description %>
</body>
<!-- This will render a full page containing a single recipe from the index page - 
index will link to each of their respetive pages containing:
name of recipe, difficulty, and a short description at minimum. 
https://guides.rubyonrails.org/routing.html for guide on 'show' pages -->

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>A little bittle about us</h1>
<h2>We're the henlos!</h2>

<div class="container">
  <div class="row justify-content-center">

    <div class="col-md-6">
    The Henlos
    </div>

    <div class="col-md-6">
    The Cats
    </div>

  </div>
</div>

app/views/static_pages/home.html.erb
<header>

  <!-- Background image -->
  <div class="p-5 text-center bg-image" style="
      background-image: url('https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2022-03/plant-based-food-mc-220323-02-273c7b.jpg');
      height: 400px;
      margin-top:100px;
    ">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
      <div class="d-flex justify-content-md-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">Your Recipes, Your Way</h1>
          <h4 class="mb-3">No more hunting down index cards.</h4>
          <a class="btn btn-outline-light btn-lg" href="#!" role="button">Explore</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>
<body>
<h2> In the beginning... </h2>
<h3>We constantly found ourselves writing recipes in random places, so we needed a place for them all. We figured you'd want that too, so here we are.</h3>
</body>

app/views/users/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 30px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
              
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                
                <%= form_with(model: @user) do |f| %>
                
                  <form class="mx-1 mx-md-4 signupForm">
                  <%= render 'shared/error_messages' %>

                  <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <%= f.label :name, "Name", class: "form-label" %>
                        <%= f.text_field :name, class: "form-control" %> 
                      </div>
                    </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :email, "Email", class: "form-label" %>
                      <%= f.email_field :email, class: "form-control" %> 
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :password, class: "form-label" %>
                      <%= f.password_field :password, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :password_confirmation, "Confirm Password", class: "form-label" %>
                      <%= f.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= f.submit "Create account", class: "btn btn-primary btn-lg" %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                <%= image_tag 'foodheart.png', class: "d-inline-block align-right" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>